#!/bin/bash

# This script is run after ~/.bash_profile
# For more information, see:
# https://docs.educates.dev/workshop-content/workshop-runtime.html#terminal-user-shell-environment

# Customize the prompt to make it easier on the eyes
export PS1_OLD="$PS1"
#export PS1="\n\[\033[33m\]\w\$ \[\033[0m\]"%
export PS1="\n\[\033[33m\][\w] $ \[\033[0m\]"
#export PS1='\n`echo -n \[\e[1\;33m\]`[\w] $ `echo \[\e[0m\]`'

# Enable finding ~/exercises/mvnw on PATH
export PATH=~/exercises:$PATH