[[fundamentals.setup]]
= 🧑‍💻 Spring Modulith Setup

[[fundamentals.setup.objectives]]
== 🎯 Objectives

You'll learn how to…

* … add the basic dependencies of Spring Modulith to your Spring Boot application.
* … create an application module within the application.
* … customize an application module's metadata.

[[fundamentals.setup.steps]]
== 👣 Build setup

Open `pom.xml` and add the Spring Modulith BOM in the `<dependencyManagement />` section.

ifndef::educates[]
[source, xml, subs="attributes+"]
----
<dependency>
	<groupId>org.springframework.modulith</groupId>
	<artifactId>spring-modulith-bom</artifactId>
	<version>${spring-modulith.version}</version>
	<type>pom</type>
	<scope>import</scope>
</dependency>
----
endif::[]

ifdef::educates[]
[source, editor:select-matching-text]
----
file: ~/exercises/pom.xml
text: "<dependencyManagement>"
before: 0
after: 4
----

[source, editor:replace-text-selection]
----
file: ~/exercises/pom.xml
text: |
		<dependencyManagement>
			<dependencies>
				<dependency>
					<groupId>org.springframework.modulith</groupId>
					<artifactId>spring-modulith-bom</artifactId>
					<version>${spring-modulith.version}</version>
					<type>pom</type>
					<scope>import</scope>
				</dependency>
			</dependencies>
		</dependencyManagement>
----
endif::[]

Add the `org.springframework:spring-modulith-starter-test` dependency in test scope to your `pom.xml`.

ifndef::educates[]
[source, xml]
----
<dependency>
	<groupId>org.springframework.modulith</groupId>
	<artifactId>spring-modulith-starter-test</artifactId>
	<scope>test</scope>
</dependency>
----
endif::[]

ifdef::educates[]
[source, editor:select-matching-text]
----
file: ~/exercises/pom.xml
text: "<!-- Spring Modulith -->"
before: 0
after: 0
----

[source, editor:replace-text-selection]
----
file: ~/exercises/pom.xml
text: |
			<dependency>
				<groupId>org.springframework.modulith</groupId>
				<artifactId>spring-modulith-starter-test</artifactId>
				<scope>test</scope>
			</dependency>
----
endif::[]

ifndef::educates[]
Run `./mvnw dependency:list -Dsort`.
endif::[]

ifdef::educates[]
Use Maven's `dependency:list` goal to list the dependencies Spring Modulith added to current project.

[source, terminal:execute]
----
command: mvnw dependency:list -Dsort | grep -v Download | grep spring-modulith
----
endif::[]

You should see that the output lists the Spring Modulith dependencies in *test scope* only.

[source, bash, subs="attributes+"]
----
[INFO] org.springframework.modulith:spring-modulith-api:jar:{spring-modulith-version}:test -- module org.springframework.modulith.api [auto]
[INFO] org.springframework.modulith:spring-modulith-core:jar:{spring-modulith-version}:test -- module org.springframework.modulith.core [auto]
[INFO] org.springframework.modulith:spring-modulith-docs:jar:{spring-modulith-version}:test -- module org.springframework.modulith.docs [auto]
[INFO] org.springframework.modulith:spring-modulith-starter-test:jar:{spring-modulith-version}:test -- module org.springframework.modulith.starter.test [auto]
[INFO] org.springframework.modulith:spring-modulith-test:jar:{spring-modulith-version}:test -- module org.springframework.modulith.test [auto]
----

[[fundamentals.creating-modules.further-ideas]]
== 💡 Further ideas
* Why are all Spring Modulith libraries scoped as test only?